[theme]
# لون الأزرار والعناصر التفاعلية
primaryColor = "#0A2859" 

# لون الخلفية الرئيسية للصفحة (لتغيير اللون الأبيض أو الأسود الافتراضي)
backgroundColor = "#E6E6FA" 

# لون الخلفية الثانوية (وهو اللون الخاص بالشريط الجانبي)
secondaryBackgroundColor = "#F0F8FF" 

# لون الخط الأساسي
textColor = "#333333"
